[package]
name = "serv"
version = "0.1.0"
authors = ["Connor Winiarczyk <connorwiniarczyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
itertools = "0.10.1"
peg = "0.7.0"
clap="2.33"
async-process="1.1.0"
http="0.2.4"
url="2.2.2"

regex="1"
lazy_static="1"
tree_magic="0.2.3"

# warp="0.3.2"
tokio = { version = "1.0", features = ["full"] }
hyper = {version = "0.14.20", features = ["full"]} 
tls-listener = { version = "0.5.1", features = ["rustls", "hyper-h1"] }
tokio-rustls = "0.23.4"
futures-util = "0.3.21"
