[package]
name = "serv"
version = "0.1.0"
authors = ["Connor Winiarczyk <connorwiniarczyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
itertools = "0.10.1"
peg = "0.7.0"
clap="2.33"
tide="0.16.0"
async-std={version="1.6.2", features=["attributes"]}
async-process="1.1.0"
http="0.2.4"

regex="1"
lazy_static="1"
