#!/bin/sh

function files { find -name "*.rs" -or -name "*.serv"; }

if [ $1 = "run" ]; then
	files | entr -r sh -c "clear && cargo run -- -ec \"hello\"";
elif [ $1 = "test" ]; then
	files | entr -r sh -c "clear && cargo test";
else
	files | entr -r sh -c "clear && cargo build";
fi
