# This is the routes.conf file that generated this server

/:
	read head.html
	shell pandoc content/index.md
	read tail.html

/content/*page:
	read head.html
	shell pandoc content/$(page).md
	read tail.html

 /self: read routes.conf

# /redirect/la: exec curl https://i.huffpost.com/gen/1271776/thumbs/o-LA-MAP-570.jpg?1



/api/date:
	exec date
	exec cowsay

/**path : read $(path)

