#!/bin/sh

echo "hello! I'm a shell script that is running as part of this api"
echo "I can do all the things a normal shell script can do"
echo 
echo "The current time is: $(date)"
echo "The current user is: $(whoami)"
echo "My file path is: $0"
echo "My arguments were: $@"

echo
echo "I can use curl too:"
result=$(curl localhost:8080/date)
echo "curl localhost:8080/date = $result"
